theme: jekyll-theme-minimal
title: Plateforme SINP Hauts-de-France
description: Documentation technique et suivi des mises à jour de la plateforme technique sinp des Hauts-de-France
header:
  image: /assets/images/header_sinp.png